# -*- coding: utf-8 -*-
"""networkdata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vtrg9G8z5BhsBvf4uvJfF9c4UPlegOg2
"""

import pandas as pd
import networkx as nx
import json
import re

df = pd.read_csv('data_scopus.csv')

df = df.fillna("")

G = nx.Graph()

nodes = []
edges = []

def getCountry(affillist, author):
    def clean_text(text):
        return re.sub(r'[^\w\s]', '', text).lower().strip()
    author_clean = clean_text(author)
    country = ""
    for entry in affillist:
        entry_clean = clean_text(entry)
        if author_clean in entry_clean:
            words = entry.split(",")
            country = words[-1]
    return country.strip()
   
for row in df.iterrows():
    affillist = row[1]['Authors with affiliations'].split("; ")
    if ";" in row[1]['Author(s) ID']:
        authors = row[1]['Author(s) ID'][:-1].split(";")
        authnames = row[1]['Authors'].split(", ")
        for author1,auth1 in zip(authors,authnames):
            affil = getCountry(affillist, auth1)
            papers = df[df['Author(s) ID'].str.contains(author1)]['EID'].values
            nodes.append((author1, {
                'Author Name': auth1,
                'Affiliation': affil,
            }))
            for author2 in authors:
                if author1 != author2:
                    edges.append((author1,author2))
                else:
                    continue
    else:
        continue

G.add_nodes_from(nodes)
G.add_edges_from(edges)

pos = nx.drawing.circular_layout(G)

nx.draw(G, pos=pos, node_size=40)

from networkx.readwrite import json_graph

with open('author_network.json', 'w') as f:
    json.dump(json_graph.node_link_data(G), f)
    

# for row in df.iterrows():
    # nodes.append((row[1]['EID'], {
        # 'Title': row[1]['Title'],
        # 'Year': row[1]['Year'],
        # 'Citations': row[1]['Cited by'],
        # 'Publisher': row[1]['Publisher'],
    # }))

# for row in df.iterrows():
    # current_paper = row[1]['EID']
    # if ";" in row[1]['Author(s) ID']:
        # authors = row[1]['Author(s) ID'][:-1].split(";")
        # for author in authors:
          # papers = df[df['Author(s) ID'].str.contains(author)]['EID'].values
          # if len(papers) > 0:
            # for paper in papers:
              # if paper != current_paper:
                # edges.append((current_paper, paper))
    # else:
        # continue

